# Generated by Django 2.1.5 on 2019-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('online', models.BooleanField(default=0, null=True)),
            ],
            options={
                'db_table': 'user_logs',
                'ordering': ['id'],
            },
        ),
    ]
