# Generated by Django 2.1.5 on 2019-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_chats',
                'ordering': ['id'],
            },
        ),
    ]
