# Generated by Django 2.1.5 on 2019-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
